import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import AuthProvider from '@/SessionProvider'
import { PostProvider } from '@/lib/PostContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        <PostProvider>
        <Navbar />
        {children}
        <Footer />
        </PostProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
